### ISSUE TITLE
Incorrect names being called by bot

### ISSUE THREAD

**Issue by Matthew-Bradley** [DongerZonie/CountPeopleSlacking#3]
In some cases the bot uses an incorrect name when referring to people who are currently working. The origin of the names used is unknown.

Example:
"Hey payday, monica,  Can you please reply with the number of people in the lab right now?"
should be
"Hey Monica,  Can you please reply with the number of people in the lab right now?

It should also be noted that there is an extra space after "monica,"

Note: The bot should also capitalize the first letter of proper names.
Note: That the bot should not capitalize the first letter of "Can".

**Comment by Matthew-Bradley** [comment]
Note that the bot should also capitalize the first letter of proper names.

**Comment by DongerZonie** [comment]
Right now that is a case of two issues; the Calendar in question having illegitimate Work Shifts and the conversion of an event title to a user name on slack. The proposed solution is to convert shift titles (workers names) into slack usernames, in order to tag them and notify them directly of a people count request.

**Comment by DongerZonie** [comment]
Resolved the capitalization that the bot itself has power over.
